### ISSUE TITLE
Log the body used for POST Operations

### ISSUE THREAD

**Issue by pcampanella** [opengeospatial/ets-ogcapi-processes10#51]
To understand where are problems, would be very useful to be able to see somewhere the Body used in the POST Operations.
This will allow to debug locally and understand better where the error is.
Would be nice to add it to the user interface while working with the docker version.

**Comment by jerstlouis** [comment]
This would really make a huge difference in trying to figure out what the ETS is reporting an error about. Without this it is next to impossible.

**Comment by gfenoy** [comment]
Actually, it is typically what we do when the ZOO-Project failed on any test, we slightly modify the source code of the specific failing test to add debugging informations. Once it is done, we use this Dockerfile to build the teamengine and the ETS locally and then we run it. During the run any invocation of System.out.println will print information in the log. So, using docker logs we can see the request body content and the URL to which it is sent.

Then, we identify on which part the issue is, is it from the ETS or from our implementation. Everything that we are able to solve on the server side is solved there, in other cases we propose PR to this ETS.

Maybe we can think of defining a generic JAVA API that would provide log capability that can be activated or deactivated on demand.

What do you think?

**Comment by jerstlouis** [comment]
@gfenoy It would be great if this capability would be built-in.
It is really, realy difficult to debug anything with the current ETS output.

A PR for this would be an extremely valuable contribution!
